name: .NET Core - Release

on:
  pull_request:
    branches: [ master ]

jobs:
  release:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 5.0.100
    - name: Install dependencies
      run: dotnet restore
    - name: Build - Windows x64
      run: dotnet publish --configuration Release --no-restore -r win-x64 /p:PublishSingleFile=true /p:IncludeNativeLibrariesForSelfExtract=true
    - name: Upload Win x64 Artifact
      uses: actions/upload-artifact@v2
      with:
        name: Cpp2IL-Win
        path: ./Cpp2IL/bin/Release/net5.0/win-x64/publish/Cpp2IL.exe
    - name: Build - Ubuntu x64
      run: dotnet publish --configuration Release --no-restore -r ubuntu-x64 /p:PublishSingleFile=true /p:IncludeNativeLibrariesForSelfExtract=true
    - name: Upload Ubuntu x64 Artifact
      uses: actions/upload-artifact@v2
      with:
        name: Cpp2IL-Linux
        path: ./Cpp2IL/bin/Release/net5.0/ubuntu-x64/publish/Cpp2IL
    - name: Build - OSX x64
      run: dotnet publish --configuration Release --no-restore -r osx-x64 /p:PublishSingleFile=true /p:IncludeNativeLibrariesForSelfExtract=true
    - name: Upload OSX x64 Artifact
      uses: actions/upload-artifact@v2
      with:
        name: Cpp2IL-Mac
        path: ./Cpp2IL/bin/Release/net5.0/osx-x64/publish/Cpp2IL
